language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t blue3197/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true blue3197/react-test-app npm run test

after_success:
  - docker build -t blue3197/docker-frontend ./frontend
  - docker build -t blue3197/docker-backend ./backend
  - docker build -t blue3197/docker-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push blue3197/docker-frontend
  - docker push blue3197/docker-backend
  - docker push blue3197/docker-nginx
